# Generated by Django 6.0.7 on 2026-07-19 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_colour', models.CharField(default='#000000', max_length=7)),
                ('widget_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.CharField(choices=[('bottom_right', 'Bottom Right'), ('bottom_left', 'Bottom Left')], default='bottom_right', max_length=20)),
                ('is_embedded_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='bots.bot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
