# Generated by Django 6.0.7 on 2026-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
