# Generated by Django 6.0.7 on 2026-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='bot_avatars/'),
        ),
        migrations.AddField(
            model_name='bot',
            name='primary_color',
            field=models.CharField(blank=True, default='#4F46E5', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Karachi', max_length=50),
        ),
    ]
