# Generated by Django 6.0.7 on 2026-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_avatar_bot_primary_color_bot_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(blank=True, choices=[('health', 'Health'), ('education', 'Education'), ('ecommerce', 'E-commerce'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('legal', 'Legal'), ('travel', 'Travel'), ('restaurant', 'Restaurant'), ('saas', 'Saas'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='tone',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('casual', 'Casual')], default='formal', max_length=50),
        ),
    ]
