# Generated by Django 5.2.16 on 2026-07-26 12:16

import bots.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_category_alter_bot_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesource',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=bots.storage.RawMediaCloudinaryStorage, upload_to='knowledge_sources/'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'Pdf'), ('text', 'Text'), ('url', 'Url'), ('youtube', 'Youtube'), ('docx', 'Word Document'), ('csv', 'CSV')], max_length=15),
        ),
    ]
