# Generated by Django 6.0.7 on 2026-08-01 08:07

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models

from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_knowledgesource_file_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='bots.bot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
