# Generated by Django 6.0.7 on 2026-08-01 10:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_emailotp_knowledgechunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
